# ==========================================
# LIFTER 1
# ==========================================

- ros_type_name: "geometry_msgs/msg/Twist"
  ros_topic_name: "/lifter1/cmd_vel"
  gz_topic_name: "/lifter1/cmd_vel"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

- ros_type_name: "nav_msgs/msg/Odometry"
  ros_topic_name: "/lifter1/odom"
  gz_topic_name: "/lifter1/odom"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

# ==========================================
# RUNNER 1
# ==========================================

- ros_type_name: "geometry_msgs/msg/Twist"
  ros_topic_name: "/runner1/cmd_vel"
  gz_topic_name: "/runner1/cmd_vel"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

- ros_type_name: "nav_msgs/msg/Odometry"
  ros_topic_name: "/runner1/odom"
  gz_topic_name: "/runner1/odom"
  gz_type_name: "ignition.msgs.Odometry"
  direction: GZ_TO_ROS

# ==========================================
# SYSTEM
# ==========================================

- ros_type_name: "rosgraph_msgs/msg/Clock"
  ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS